### ISSUE TITLE
Linking package with no script section

### ISSUE THREAD

**Issue by marinatells** [artifact-project/npmy#7]
package
```
{
  "name": "package",
  "version": "0.0.0",
  "description": "Clone of autolink2 with mrg modifications",
  "main": "index.js"
}
```

result
```
Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'hasOwnProperty' of undefined
    at ObservablePackage.hasHook (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:33:34)
    at ObservablePackage.<anonymous> (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:37:22)
    at Generator.next (<anonymous>)
    at /Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:3:12)
    at ObservablePackage.execHook (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:36:16)
    at addTask (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/ObservablePackage/ObservablePackage.js:42:33)
    at ObservablePackage.<anonymous> (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/ObservablePackage/ObservablePackage.js:152:27)
    at Generator.next (<anonymous>) } reason: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at ObservablePackage.hasHook (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:33:34)
    at ObservablePackage.<anonymous> (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:37:22)
    at Generator.next (<anonymous>)
    at /Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:3:12)
    at ObservablePackage.execHook (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/Package/Package.js:36:16)
    at addTask (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/ObservablePackage/ObservablePackage.js:42:33)
    at ObservablePackage.<anonymous> (/Users/marinatells/.nvm/versions/node/v8.10.0/lib/node_modules/npmy/src/ObservablePackage/ObservablePackage.js:152:27)
    at Generator.next (<anonymous>)
```

works
```
{
  "name": "package",
  "version": "0.0.0",
  "description": "Clone of autolink2 with mrg modifications",
  "main": "index.js",
  "scripts": {}
}
```

**Comment by RubaXa** [comment]
+ npmy@0.6.4
